### PR TITLE
PR : Form validation for registration screen

### LINKED ISSUE #4: Form validation for registration screen.
All the fields are required.
**Password** field should match the **Confirm password** field.

Try to "disable" a submit button if validation fails.

### PR DESCRIPTION
**Pull request by RobinKim-SWEngineer**
## What is it about?
 - Validation of user inputs for registration
 - Checkpoints
    - Any form is empty
    - Email address is valid ( includes '@')
    - Confirmation password mathes with original one

## How is it written?
 - With `TextEditingController` validating user inputs.

## How to test it?
 - Press the REGISTER button before entering data, it will show that all forms are invalid.
 - As the user enters data, each form will automatically check the validity. 

## Sample image?
validation_image1

### CODE REVIEW

File: lib/Screens/AuthRegistration/support_widgets.dart [hunk 1]
```diff
@@ -30,46 +32,63 @@ class SignInTab extends StatelessWidget {
...
-            child: Text(
-              'Sign In',
-              style: TextStyle(
-                fontWeight: FontWeight.bold,
-                fontSize: 16,
-                color: Colors.white,
-              ),
-            ))
+          onPressed: () {
+            keyRegisterationButton.currentState!.changeButtonText('Boo');
```
Comment (AndreyKalashnik) [inline lib/Screens/AuthRegistration/support_widgets.dart]: didn't worked with referencing on the other widget states, TBH. And I'm not sure if it is legal haha.
But OK, if it crying about NULL, wrap it inside of NULL check, like this 
if (keyRegisterationButton.currentState != null) {
  keyRegisterationButton.currentState!.changeButtonText('Boo');
}

**Review by AndreyKalashnik — CHANGES_REQUESTED** [review]

File: lib/Screens/AuthRegistration/support_widgets.dart (hunk 1 above)
Comment (RobinKim-SWEngineer) [reply lib/Screens/AuthRegistration/support_widgets.dart]: Yes,  `keyRegisterationButton.currentState` is null. That's why the code is not working. But I don't know why it is null when I initialized above like this. `GlobalKey<RegistrationButtonState> keyRegisterationButton = GlobalKey();` :(

File: lib/Screens/AuthRegistration/body.dart [hunk 2]
```diff
@@ -8,126 +9,204 @@ class Body extends StatefulWidget {
...
+  Widget _buildPasswordInputFrame() => Column(
+        crossAxisAlignment: CrossAxisAlignment.start,
+        children: [
+          Text(
+            'Password',
+            style: labelTextStyle,
+          ),
+          SizedBox(height: 5),
+          Container(
+            child: TextFormField(
```
Comment (AndreyKalashnik) [inline lib/Screens/AuthRegistration/body.dart]: In this case you could use a `TextEditingController` in stateful widget. I'm not saying your approach is wrong, but a bit more complicated :)

```
final TextEditingController _nameController = TextEditingController();

@override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

And inside of `build` method:

TextFormField(
    controller: _nameController,
    decoration: InputDecoration(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.all(
          Radius.circular(12),
        ),
      ),
      labelText: 'Name label',
      hintText: 'Name hint',
    ),
    validator: (value) {
      if (value == null || value.isEmpty) {
        return 'Please enter the name';
      }
      return null;
    },
  ),```

**Review by AndreyKalashnik — APPROVED** [review]
App is crushing... need to check it out.

I would put the body.dart, input_validator and support_widgets in components folder.

File: lib/Screens/AuthRegistration/body.dart (hunk 2 above)
Comment (RobinKim-SWEngineer) [reply lib/Screens/AuthRegistration/body.dart]: Refactoring done : `TextEditingController` instead of "GlobalKey with Form widget"

File: lib/Screens/AuthRegistration/auth_registartion_screen.dart [hunk 3]
```diff
@@ -1,12 +1,18 @@
...
+//import 'package:demo/Screens/AuthRegistration/components/body.dart';
+import 'package:demo/Screens/AuthRegistration/components/body_refactored.dart';
 
-class AuthRegistrationScreen extends StatelessWidget {
+class AuthRegistrationScreen extends StatefulWidget {
+  @override
+  _AuthRegistrationScreen createState() => _AuthRegistrationScreen();
+}
+
+class _AuthRegistrationScreen extends State<AuthRegistrationScreen> {
```
Comment (AndreyKalashnik) [inline lib/Screens/AuthRegistration/auth_registartion_screen.dart]: Do you need a state here?

**Review by AndreyKalashnik — CHANGES_REQUESTED** [review]
+729 −262 (almost 1000) lines changed. As soon as PR's overlaps 300 lines, they become hard to track. This number (1000) can tell you, that
1. You could chop your PR into smaller and make it more "modular";
2. Possibly you went in the not most efficient way to solve the issue;
3. You probably forgot to remove some huge commented file, like this lib/Screens/AuthRegistration/components/body.dart 😄 

Of course, It's totally fine for now :) You are learning it!

File: lib/Screens/AuthRegistration/auth_registartion_screen.dart (hunk 3 above)
Comment (RobinKim-SWEngineer) [reply lib/Screens/AuthRegistration/auth_registartion_screen.dart]: No need! Corrected into `StatelessWidget!`

**Review by AndreyKalashnik — APPROVED** [review]
👍 yeah baby!
